GET http://localhost:3000/myPage
Content-Type: application/json
accessToken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3d3dy5iYWxsb2cuY29tIiwic3ViIjoia2FrYW8zNjI5MTA4NDI4IiwiaWF0IjoxNzIyMDI5MDg5LCJleHAiOjE3MjIwMzYyODl9.klRDvH_PV69utn4gtmPswKHYHA4z-k1TKpnPolvwey8
refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjE5OTQ4NzEsImV4cCI6MTcyMzIwNDQ3MX0.nA2UKq3zNLOrc9pOVaBBHg4xnySt8imAPP7VqIGGxUI