name: Node.js Dev CI/CD

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "SECRET=${{ secrets.SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI_LOGIN=${{ secrets.GOOGLE_REDIRECT_URI_LOGIN }}" >> .env
          echo "GOOGLE_REDIRECT_URI_SIGN_UP=${{ secrets.GOOGLE_REDIRECT_URI_SIGN_UP }}" >> .env
          echo "GOOGLE_TOKEN_URL=${{ secrets.GOOGLE_TOKEN_URL }}" >> .env
          echo "GOOGLE_USERINFO_URL=${{ secrets.GOOGLE_USERINFO_URL }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
          echo "KAKAO_REDIRECT_URI_LOGIN=${{ secrets.KAKAO_REDIRECT_URI_LOGIN }}" >> .env
          echo "KAKAO_REDIRECT_URI_SIGN_UP=${{ secrets.KAKAO_REDIRECT_URI_SIGN_UP }}" >> .env
          echo "KAKAO_TOKEN_URL=${{ secrets.KAKAO_TOKEN_URL }}" >> .env
          echo "KAKAO_USERINFO_URL=${{ secrets.KAKAO_USERINFO_URL }}" >> .env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "NAVER_REDIRECT_URI_LOGIN=${{ secrets.NAVER_REDIRECT_URI_LOGIN }}" >> .env
          echo "NAVER_REDIRECT_URI_SIGN_UP=${{ secrets.NAVER_REDIRECT_URI_SIGN_UP }}" >> .env
          echo "NAVER_TOKEN_URL=${{ secrets.NAVER_TOKEN_URL }}" >> .env
          echo "NAVER_USERINFO_URL=${{ secrets.NAVER_USERINFO_URL }}" >> .env
          echo "AWS_IAM_KEY=${{ secrets.AWS_IAM_KEY }}" >> .env
          echo "AWS_IAM_SECRET_KEY=${{ secrets.AWS_IAM_SECRET_KEY }}" >> .env

      - name: Run Build
        run: npm run build

      - name: Generate deployment package
        run: |
          cp -R .platform dist
          cp package.json dist/package.json
          cp Procfile dist/Procfile
          cd dist
          zip -r deploy.zip .

      - name: Get Zip Inside
        run: zipinfo -1 dist/deploy.zip

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
          application_name: Ballog-develop
          environment_name: Ballog-develop-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          use_existing_version_if_available: false
          region: ap-northeast-2
          deployment_package: dist/deploy.zip
          wait_for_deployment: false

      - name: Deployed!
        run: echo App deployed to ELB
